use crate::parser::Atom;
use std::fs;
use std::path::Path;

pub fn transpile(atom: &Atom, output_path: &Path) -> Result<(), String> {
    let mut go_code = String::new();

    // 1. パッケージ宣言
    go_code.push_str("package mumei\n\n");

    // --- 修正ポイント: 必要な時だけインポートする ---
    // 今後 forall や exists などの高度な検証が増えることも見越し、
    // 「ランタイムチェックが必要か」をフラグで管理します。
    let needs_fmt = atom.requires.contains("b != 0") || !atom.forall_constraints.is_empty();

    if needs_fmt {
        go_code.push_str("import \"fmt\"\n\n");
    }

    // 2. 自動生成コメント
    go_code.push_str(&format!("// {} is a mathematically verified function by Mumei.\n", atom.name));
    go_code.push_str(&format!("// Requires: {}\n", atom.requires));
    go_code.push_str("// Do not edit this file manually.\n");

    // 3. 関数シグネチャ
    let params = atom.params.iter()
        .map(|p| format!("{} int32", p))
        .collect::<Vec<_>>()
        .join(", ");

    go_code.push_str(&format!("func {}({}) int32 {{\n", atom.name, params));

    // 4. ランタイム・アサーション
    if atom.requires.contains("b != 0") {
        go_code.push_str("    // Safety Check: Pre-condition verified by Z3\n");
        go_code.push_str("    if b == 0 {\n");
        // ここで fmt を使用
        go_code.push_str(&format!("        panic(fmt.Sprintf(\"Mumei Logic Error: Pre-condition 'b != 0' violated in {}\"))\n", atom.name));
        go_code.push_str("    }\n");
    }

    // TODO: 今後、forall_constraints を使ったループバリデーションもここに fmt を使って実装する

    // 5. ロジック本体
    go_code.push_str(&format!("    return {}\n", atom.body_expr));
    go_code.push_str("}\n");

    // 6. ファイル書き出し
    let go_file_path = output_path.with_extension("go");
    fs::write(&go_file_path, go_code).map_err(|e| e.to_string())?;

    Ok(())
}