use crate::parser::Atom;
use std::fs;
use std::path::Path;

/// MumeiのAtomをGoのソースコードに変換する
pub fn transpile(atom: &Atom, output_path: &Path) -> Result<(), String> {
    let mut go_code = String::new();

    // 1. パッケージ宣言と標準ライブラリのインポート
    go_code.push_str("package mumei\n\n");
    go_code.push_str("import \"fmt\"\n\n");

    // 2. 自動生成コメントとドキュメント
    go_code.push_str(&format!("// {} is a mathematically verified function by Mumei.\n", atom.name));
    go_code.push_str(&format!("// Requires: {}\n", atom.requires));
    go_code.push_str("// Do not edit this file manually.\n");

    // 3. 関数シグネチャの構築 (Goでは型を後ろに書く)
    // Mumeiの引数は基本的に int32 として扱います
    let params = atom.params.iter()
        .map(|p| format!("{} int32", p))
        .collect::<Vec<_>>()
        .join(", ");

    go_code.push_str(&format!("func {}({}) int32 {{\n", atom.name, params));

    // 4. ランタイム・アサーション (Runtime Safeguard)
    // 検証済み条件(requires)を、実行時の防壁として埋め込みます
    // ※現在は簡易的に "b != 0" のみを検知していますが、将来的にはパーサーが複雑な条件も変換します
    if atom.requires.contains("b != 0") {
        go_code.push_str("    // Safety Check: Pre-condition verified by Z3\n");
        go_code.push_str("    if b == 0 {\n");
        go_code.push_str(&format!("        panic(fmt.Sprintf(\"Mumei Logic Error: Pre-condition 'b != 0' violated in {} corresponds to requires clause.\"))\n", atom.name));
        go_code.push_str("    }\n");
    }

    // 5. ロジック本体
    // Goの文法に合わせて出力
    go_code.push_str(&format!("    return {}\n", atom.body_expr));
    go_code.push_str("}\n");

    // 6. ファイル書き出し (.go)
    // output_path が "output/katana" なら "output/katana.go" になる
    let go_file_path = output_path.with_extension("go");
    fs::write(&go_file_path, go_code).map_err(|e| e.to_string())?;

    Ok(())
}